services:
  server:
    build:
      context: .
      dockerfile: src/server/Dockerfile
  
  cpp-client:
    build:
      context: .
      dockerfile: src/client/Dockerfile.cpp

  py-client:
    build:
      context: .
      dockerfile: src/client/Dockerfile.py
  gtest:
    build:
      context: .
      dockerfile: tests/Dockerfile
