services:
  base-server:
    build:
      context: base/
      dockerfile: Dockerfile

  base-client-cpp:
    build:
      context: base/
      dockerfile: src/client/Dockerfile.cpp

  base-client-py:
    build:
      context: base/
      dockerfile: src/client/Dockerfile.py

  base-tests:
    build:
      context: base/
      dockerfile: tests/Dockerfile

  api-server:
    build:
      context: api/
      dockerfile: Dockerfile
