services:
  gtest:
    build:
      context: ./tests
      dockerfile: Dockerfile
    env_file:
      - tests/.env
  
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    env_file:
      - .env